### ISSUE TITLE
How to run the java code

### ISSUE THREAD

**Issue by kickbox** [Microos/FaceAnnotationTool#1]
I am trying to start the tool , am not familiar with java, please help

**Comment by gox-ai** [comment]
Any update on this?

**Comment by Microos** [comment]
Hi @kickbox @gox-ai, you can simply download the release from https://github.com/Microos/FaceAnnotationTool/releases/tag/v0.11

Make sure you have JRE installed and then you are good to go.

**Comment by gox-ai** [comment]
Thank you so much!
